name: Main Workflow
on:
  schedule:
    - cron:  '*/55 * * * *'
jobs:
  Ubuntu:
    name: Add labels to overdue issues
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Issue Due Dates Action
        uses: mabrahamdevops/blog-due-dates
        with:
          GH_TOKEN: "${{ secrets.GH_TOKEN }}"